fileVersion: 1
id: "2"
mappingDefinitions:
  SRC:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  STG:
    database: SHRUTHI_5_4QA
    schema: QA_5_4
name: New Environment
type: Environment
