fileVersion: 1
id: "2"
mappingDefinitions:
  SRC:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  STG:
    database: SHRUTHI_DB
    schema: PUBLIC
name: New Environment
type: Environment
