@id("8f951e52-d0f6-4597-94ef-6a8d67f2b829")
@nodeType("b14186e6-5c99-4612-bbec-5f3478aadfd9")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT"
FROM {{ ref('SAMPLE', 'ORDERS') }} "ORDERS"