@id("1308edc5-1bdd-4c1c-a38f-39d46400f901")
@nodeType("b14186e6-5c99-4612-bbec-5f3478aadfd9")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT"
FROM {{ ref('SAMPLE', 'ORDERS') }} "ORDERS"